bool validarCadena(string cadena);
bool validarNombreApellido(string nombreApellido);
string convertirPM(string cadena);
bool validarFecha(string dia, string mes, string anio);
bool validarAnio(string anio);
double validarSueldo(string sueldo);
bool validarNumero(string numero);
bool validarEdad(string edad);
bool validarOpcion(string nivel, string tipo);
bool validarOpcion(string op, int cant);
string validarRespuesta(string resp);